### ISSUE TITLE
[BUG] Argument Exception when trying to empty a bucket

### ISSUE THREAD

**Issue by c0der4t** [c0der4t/S3-SimpleBackup#5]
04/04/2023 11:10:34:01	Deleting all objects in bucket 
04/04/2023 11:10:34:37	An error occurred
:System.ArgumentException: BucketName is a required property and must be set before making this call. (Parameter 'ListObjectsV2Request.BucketName')
   at Amazon.S3.Model.Internal.MarshallTransformations.ListObjectsV2RequestMarshaller.Marshall(ListObjectsV2Request listObjectsRequest)
   at Amazon.S3.Model.Internal.MarshallTransformations.ListObjectsV2RequestMarshaller.Marshall(AmazonWebServiceRequest input)
   at Amazon.Runtime.Internal.Marshaller.PreInvoke(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Marshaller.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.S3.Internal.AmazonS3ExceptionHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)
   at S3_SimpleBackup.S3Methods.DeleteAllObjectsinBucket(String s3Host, String s3AccessKey, SecureString s3SecureKey, String bucketToTarget, Window parentWindow) in C:\Users\lab_services_student\dev\S3-SimpleBackup\S3Methods.cs:line 292

Please try again

**Comment by c0der4t** [comment]
This was due to a textbox that was renamed, but the rename was not done in the btnEmptyBucket_Clicked method. This has been fixed
